module com.projectswg.common {
	requires transitive me.joshlarson.jlcommon;
	requires static java.sql;
	requires static java.desktop;
	requires transitive java.management;
	requires org.mongodb.bson;
	requires org.jetbrains.annotations;
	requires org.bouncycastle.provider;
	requires kotlin.stdlib;
	
	exports com.projectswg.common.data;
	exports com.projectswg.common.data.combat;
	exports com.projectswg.common.data.customization;
	exports com.projectswg.common.data.encodables.chat;
	exports com.projectswg.common.data.encodables.galaxy;
	exports com.projectswg.common.data.encodables.gcw;
	exports com.projectswg.common.data.encodables.map;
	exports com.projectswg.common.data.encodables.mongo;
	exports com.projectswg.common.data.encodables.oob;
	exports com.projectswg.common.data.encodables.oob.waypoint;
	exports com.projectswg.common.data.encodables.player;
	exports com.projectswg.common.data.encodables.tangible;
	exports com.projectswg.common.data.info;
	exports com.projectswg.common.data.location;
	exports com.projectswg.common.data.math;
	exports com.projectswg.common.data.math.extents;
	exports com.projectswg.common.data.objects;
	exports com.projectswg.common.data.radial;
	exports com.projectswg.common.data.schematic;
	exports com.projectswg.common.data.sui;
	exports com.projectswg.common.data.swgfile;
	exports com.projectswg.common.data.swgfile.visitors;
	exports com.projectswg.common.data.swgfile.visitors.appearance;
	exports com.projectswg.common.data.swgfile.visitors.appearance.render;
	exports com.projectswg.common.data.swgfile.visitors.shader;
	exports com.projectswg.common.data.swgiff;
	exports com.projectswg.common.data.swgiff.parsers;
	exports com.projectswg.common.data.swgiff.parsers.appearance;
	exports com.projectswg.common.data.swgiff.parsers.appearance.extents;
	exports com.projectswg.common.data.swgiff.parsers.footprint;
	exports com.projectswg.common.data.swgiff.parsers.math;
	exports com.projectswg.common.data.swgiff.parsers.misc;
	exports com.projectswg.common.data.swgiff.parsers.terrain;
	exports com.projectswg.common.encoding;
	exports com.projectswg.common.network;
	exports com.projectswg.common.network.packets;
	exports com.projectswg.common.network.packets.swg;
	exports com.projectswg.common.network.packets.swg.admin;
	exports com.projectswg.common.network.packets.swg.holo;
	exports com.projectswg.common.network.packets.swg.holo.login;
	exports com.projectswg.common.network.packets.swg.login;
	exports com.projectswg.common.network.packets.swg.login.creation;
	exports com.projectswg.common.network.packets.swg.zone;
	exports com.projectswg.common.network.packets.swg.zone.auction;
	exports com.projectswg.common.network.packets.swg.zone.baselines;
	exports com.projectswg.common.network.packets.swg.zone.building;
	exports com.projectswg.common.network.packets.swg.zone.chat;
	exports com.projectswg.common.network.packets.swg.zone.combat;
	exports com.projectswg.common.network.packets.swg.zone.crafting.resources;
	exports com.projectswg.common.network.packets.swg.zone.crafting.surveying;
	exports com.projectswg.common.network.packets.swg.zone.deltas;
	exports com.projectswg.common.network.packets.swg.zone.guild;
	exports com.projectswg.common.network.packets.swg.zone.harvesters;
	exports com.projectswg.common.network.packets.swg.zone.insertion;
	exports com.projectswg.common.network.packets.swg.zone.object_controller;
	exports com.projectswg.common.network.packets.swg.zone.object_controller.combat;
	exports com.projectswg.common.network.packets.swg.zone.object_controller.loot;
	exports com.projectswg.common.network.packets.swg.zone.resource;
	exports com.projectswg.common.network.packets.swg.zone.server_ui;
	exports com.projectswg.common.network.packets.swg.zone.spatial;
	exports com.projectswg.common.network.packets.swg.zone.trade;
	exports com.projectswg.common.persistable;
	exports com.projectswg.common.process;
	exports com.projectswg.common.utilities;
}
